version: '3'
services:
  app:
    container_name: blagues_api
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./blagues.json:/app/blagues.json
    env_file:
      - ./.env
    ports:
      - '4003:4000'
    depends_on:
      - postgres
    networks:
      - global

  website:
    container_name: blagues_api.fr
    restart: unless-stopped
    build:
      context: ../blagues-api.fr/
      dockerfile: ./docker/Dockerfile
    tty: true
    env_file:
      - ../blagues-api.fr/.env
    depends_on:
      - app
    ports:
      - '3003:3000'

  postgres:
    container_name: blagues_api_postgres
    restart: unless-stopped
    image: 'postgres:13'
    volumes:
      - ./databases/postgres:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - '5440:5432'
    networks:
      - global

networks:
  global:
